name: Verify PR - Code Lint
on: [pull_request]

jobs:
  lint:
    name: Code Lint (ESLint)
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install Node Modules
        run: yarn install --frozen-lockfile

      - name: Lint Project
        run: yarn lint
