name: Verify PR - No Istanbul Ignore
on: [pull_request]

jobs:
  no-istanbul-ignore:
    name: No Istanbul Ignore Comments (Coverage)
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Lint Project
        run: npx no-istanbul-ignore src
