name: Verify PR - Unit Tests
on: [pull_request]

jobs:
  unit-tests:
    name: Unit Tests (Jest)
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install Node Modules
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test:ci

      - name: Post Coverage Results to Pull Request
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
